teams:
  - name: indy-admin
    maintainers:
      - ryjones
    members:
      - WadeBarnes
      - swcurran
#    members:
      - PatStLouis
      - TelegramSam
      - Toktar
      - andrewwhitehead
      - KimEbert42
      - lynnbendixsen
#  - name: indy-agent-maintainers
#    maintainers:
#      - TelegramSam
#    members:
#      - dbluhm
#  - name: indy-besu-maintainers
#    maintainers:
#      - Artemkaaas
#      - ashcherbakov
#    members:
#      - akarabashov
#      - Toktar
#  - name: indy-ci
#    maintainers:
#      - WadeBarnes
#    members:
#      - sovbot
#  - name: indy-ci-maintainers
#    maintainers:
#      - WadeBarnes
#  - name: indy-cli-rs-maintainers
#    maintainers:
#      - WadeBarnes
#      - swcurran
#    members:
#      - Artemkaaas
#      - andrewwhitehead
#      - ashcherbakov
#  - name: indy-common
#    maintainers:
#      - WadeBarnes
#      - mikelodder7
#    members:
#      - Toktar
#      - esune
#  - name: indy-did-method-maintainers
#    maintainers:
#      - swcurran
#    members:
#      - dbluhm
#  - name: indy-did-network-maintainers
#    maintainers:
#      - WadeBarnes
#      - swcurran
#    members:
#      - Echsecutor
#      - lynnbendixsen
#  - name: indy-node-container-maintainers
#    maintainers:
#      - Echsecutor
#      - swcurran
#    members:
#      - c2bo
#      - mgmgwi
#  - name: indy-node-monitor-maintainers
#    maintainers:
#      - WadeBarnes
#    members:
#      - swcurran
#  - name: indy-plenum-maintainers
#    maintainers:
#      - WadeBarnes
#      - andrewwhitehead
#    members:
#      - PatStLouis
#  - name: indy-rfc-maintainers
#    maintainers:
#      - TelegramSam
#    members:
#      - mikelodder7
#  - name: indy-sdk-contributors
#    maintainers:
#      - Patrik-Stas
#    members:
#      - Artemkaaas
#      - mikelodder7
#  - name: indy-sdk-python-maintainers
#    maintainers:
#      - TelegramSam
#      - andrewwhitehead
#  - name: indy-sdk-react-native-maintainers
#    maintainers:
#      - TimoGlastra
#  - name: indy-security
#    maintainers:
#      - ryjones
#  - name: indy-shared-gha-maintainers
#    maintainers:
#      - WadeBarnes
#  - name: indy-shared-rs-maintainers
#    maintainers:
#      - WadeBarnes
#    members:
#      - andrewwhitehead
#  - name: indy-test-automation
#    maintainers:
#      - WadeBarnes
#    members:
#      - Toktar
#      - swcurran
#  - name: indy-vdr-maintainers
#    maintainers:
#      - WadeBarnes
#      - swcurran
#    members:
#      - Artemkaaas
#      - TimoGlastra
#      - andrewwhitehead
#      - berendsliedrecht
#      - ianco
  - name: lf-employees
    maintainers:
      - ryjones
    members:
      - thelinuxfoundation
      - hartm
      - jwagantall
      - davidwboswell
repositories:
  - name: governance
    teams:
      indy-admin: maintain
      lf-employees: maintain
    visibility: public
#  - name: indy
#    teams:
#      indy-admin: admin
#    visibility: public
#  - name: indy-besu
#    teams:
#      indy-admin: admin
#      indy-agent-maintainers: write
#      indy-besu-maintainers: admin
#      indy-ci: write
#      indy-ci-maintainers: write
#      indy-cli-rs-maintainers: write
#      indy-common: write
#      indy-did-method-maintainers: write
#      indy-did-network-maintainers: write
#      indy-node-container-maintainers: write
#      indy-node-monitor-maintainers: write
#      indy-plenum-maintainers: write
#      indy-rfc-maintainers: write
#      indy-sdk-contributors: write
#      indy-sdk-python-maintainers: write
#      indy-sdk-react-native-maintainers: write
#      indy-shared-gha-maintainers: write
#      indy-shared-rs-maintainers: write
#      indy-test-automation: write
#      indy-vdr-maintainers: write
#    visibility: public
#  - name: indy-bls-wrapper-python
#    teams:
#      indy-admin: admin
#      indy-vdr-maintainers: maintain
#    visibility: public
#  - name: indy-blssignatures-rs
#    teams:
#      indy-admin: admin
#      indy-plenum-maintainers: maintain
#      indy-vdr-maintainers: maintain
#    visibility: public
#  - name: indy-cli-rs
#    teams:
#      indy-admin: admin
#      indy-cli-rs-maintainers: maintain
#      indy-common: read
#    visibility: public
#  - name: indy-did-method
#    teams:
#      indy-admin: admin
#      indy-common: read
#      indy-did-method-maintainers: admin
#    visibility: public
#  - name: indy-did-networks
#    teams:
#      indy-did-network-maintainers: admin
#    visibility: public
#  - name: indy-docs
#    teams:
#      indy-admin: admin
#      indy-ci: write
#      indy-common: read
#    visibility: public
#  - name: indy-hipe
#    teams:
#      indy-admin: admin
#      indy-common: read
#      indy-rfc-maintainers: maintain
#    visibility: public
#  - name: indy-node
#    teams:
#      indy-admin: admin
#      indy-agent-maintainers: maintain
#      indy-besu-maintainers: maintain
#      indy-ci: maintain
#      indy-ci-maintainers: maintain
#      indy-cli-rs-maintainers: maintain
#      indy-common: maintain
#      indy-did-method-maintainers: maintain
#      indy-did-network-maintainers: maintain
#      indy-node-container-maintainers: maintain
#      indy-node-monitor-maintainers: maintain
#      indy-plenum-maintainers: maintain
#      indy-rfc-maintainers: maintain
#      indy-sdk-contributors: maintain
#      indy-sdk-python-maintainers: maintain
#      indy-sdk-react-native-maintainers: maintain
#      indy-shared-gha-maintainers: maintain
#      indy-shared-rs-maintainers: maintain
#      indy-test-automation: maintain
#      indy-vdr-maintainers: maintain
#    visibility: public
#  - name: indy-node-container
#    teams:
#      indy-admin: admin
#      indy-common: read
#      indy-node-container-maintainers: maintain
#    visibility: public
#  - name: indy-node-monitor
#    teams:
#      indy-admin: admin
#      indy-common: read
#      indy-node-monitor-maintainers: maintain
#      indy-shared-rs-maintainers: read
#    visibility: public
#  - name: indy-plenum
#    teams:
#      indy-admin: admin
#      indy-agent-maintainers: maintain
#      indy-besu-maintainers: maintain
#      indy-ci: maintain
#      indy-ci-maintainers: maintain
#      indy-cli-rs-maintainers: maintain
#      indy-common: maintain
#      indy-did-method-maintainers: maintain
#      indy-did-network-maintainers: maintain
#      indy-node-container-maintainers: maintain
#      indy-node-monitor-maintainers: maintain
#      indy-plenum-maintainers: maintain
#      indy-rfc-maintainers: maintain
#      indy-sdk-contributors: maintain
#      indy-sdk-python-maintainers: maintain
#      indy-sdk-react-native-maintainers: maintain
#      indy-shared-gha-maintainers: maintain
#      indy-shared-rs-maintainers: maintain
#      indy-test-automation: maintain
#      indy-vdr-maintainers: maintain
#    visibility: public
#  - name: indy-shared-gha
#    teams:
#      indy-admin: admin
#      indy-common: read
#      indy-shared-gha-maintainers: admin
#    visibility: public
#  - name: indy-shared-rs
#    teams:
#      indy-admin: admin
#      indy-common: read
#      indy-shared-rs-maintainers: maintain
#    visibility: public
#  - name: indy-test-automation
#    teams:
#      indy-admin: admin
#      indy-common: read
#      indy-test-automation: maintain
#    visibility: public
#  - name: indy-vdr
#    teams:
#      indy-admin: admin
#      indy-common: read
#      indy-shared-rs-maintainers: read
#      indy-vdr-maintainers: maintain
#    visibility: public
