teams:
  - name: indy-admin
    maintainers:
      - WadeBarnes
      - swcurran
    members:
      - PatStLouis
      - TelegramSam
      - Toktar
      - andrewwhitehead
      - KimEbert42
      - lynnbendixsen
  - name: lf-employees
    maintainers:
      - ryjones
    members:
      - thelinuxfoundation
      - hartm
      - jwagantall
      - davidwboswell
repositories:
  - name: governance
    teams:
      indy-admin: maintain
      lf-employees: maintain
    visibility: public
  - name: indy
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-besu
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-bls-wrapper-python
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-blssignatures-rs
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-cli-rs
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-did-method
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-did-networks
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-docs
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-hipe
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-node
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-node-container
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-node-monitor
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-plenum
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-shared-gha
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-shared-rs
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-test-automation
    teams:
      indy-admin: admin
    visibility: public
  - name: indy-vdr
    teams:
      indy-admin: admin
    visibility: public
